(() => {
  function clean(s){return String(s??'').toLowerCase().replace(/[−–—]/g,'-').replace(/[×·]/g,'*').replace(/÷/g,'/').replace(/’/g,"'").replace(/\s+/g,' ').trim()}
  function compact(s){return clean(s).replace(/[$£€,%°]/g,'').replace(/\s*([=+\-*/^(){}\[\],:])\s*/g,'$1').replace(/[.!?]/g,'').trim()}
  function primary(s){return clean(s).split(/\s+(?:—|–|-|because|since|so|where|which means|the set of|all whole numbers)\s+/i)[0].replace(/[.!?]$/,'').trim()}
  function lev(a,b){a=clean(a);b=clean(b);const m=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=m[0];m[0]=i;for(let j=1;j<=b.length;j++){const tmp=m[j];m[j]=Math.min(m[j]+1,m[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=tmp}}return m[b.length]}
  function number(s){const c=compact(s).replace(/^[a-z]+=/,'');return /^-?\d+(?:\.\d+)?$/.test(c)?Number(c):null}
  function match(user,expected){const u=clean(user),e=clean(expected),uc=compact(user),ec=compact(expected);if(!u)return false;if(uc===ec)return true;const un=number(user),en=number(expected);if(un!==null&&en!==null&&Math.abs(un-en)<1e-9)return true;const p=primary(expected),pc=compact(p);if(uc===pc)return true;const pn=number(p);if(un!==null&&pn!==null&&Math.abs(un-pn)<1e-9)return true;if(/^(yes|no)\b/.test(p)&&u===p.split(/\s+/)[0])return true;const phrase=p.replace(/^(an?|the)\s+/,'').trim();if(phrase.length>=3&&(u===phrase||e.startsWith(u+' —')||e.startsWith(u+' -')))return true;const target=phrase.split(/[,:;(]/)[0].trim();if(u.length>=4&&target.length>=4&&u.split(' ').length<=3&&target.split(' ').length<=3){const allowance=Math.max(u.length,target.length)>=9?2:1;if(lev(u,target)<=allowance)return true}return false}
  window.studyAnswersMatch=match;
  function patch(){const learn=document.getElementById('learnCheck'),test=document.getElementById('testSubmit');if(learn&&!learn.dataset.flexPatched){learn.dataset.flexPatched='1';learn.addEventListener('click',()=>{setTimeout(()=>{const fb=document.getElementById('learnFeedback'),input=document.getElementById('learnWritten');if(!fb||!input||!/^not quite/i.test(fb.textContent.trim()))return;const m=fb.textContent.match(/Answer:\s*(.+)$/i);if(m&&match(input.value,m[1])){fb.innerHTML='<b>✓ Correct!</b> Equivalent answer accepted.';const d=typeof ensureData==='function'?ensureData():null;if(d){d.learnStats||={};const topic=document.getElementById('learnDeck')?.value;if(topic&&d.learnStats[topic]){d.learnStats[topic].wrong=Math.max(0,(d.learnStats[topic].wrong||0)-1);d.learnStats[topic].right=(d.learnStats[topic].right||0)+1;saveData(d)}}}},0)},true)}
    if(test&&!test.dataset.flexPatched){test.dataset.flexPatched='1';test.addEventListener('click',()=>{const typed=document.getElementById('testAnswer')?.value;setTimeout(()=>{const fb=document.getElementById('testFeedback');if(!fb||!/^incorrect/i.test(fb.textContent.trim()))return;const expected=fb.textContent.replace(/^incorrect\.\s*/i,'');if(match(typed,expected)){fb.innerHTML='<b>✓ Correct</b> Equivalent answer accepted.'}},0)},true)}
  }
  patch();new MutationObserver(patch).observe(document.body,{childList:true,subtree:true});
})();