(() => {
  const $=id=>document.getElementById(id);
  const plants={sunflower:{name:'Sunflower',full:'🌻',stages:['🟤','🌱','🌿','🌿🟢','🌻']},cactus:{name:'Cactus',full:'🌵',stages:['🟤','🌱','🌵','🌵🌵','🌵🌸']},flower:{name:'Cherry Blossom',full:'🌸',stages:['🟤','🌱','🌿','🌷','🌸']}};
  const fresh=()=>({active:'sunflower',minutes:0,growthStage:1,garden:[],justCompleted:false});
  function stage(min){return min>=120?5:min>=75?4:min>=50?3:min>=25?2:1}
  function state(){if(!currentUser)return fresh();const d=ensureData();d.gardenSystem=Object.assign(fresh(),d.gardenSystem||{});d.gardenSystem.garden=Array.isArray(d.gardenSystem.garden)?d.gardenSystem.garden:[];d.gardenSystem.growthStage=stage(d.gardenSystem.minutes);saveData(d);return d.gardenSystem}
  function saveState(s){if(!currentUser)return;s.growthStage=stage(s.minutes);const d=ensureData();d.gardenSystem=s;saveData(d)}
  function wait(n=60){const view=$('view-timer');if(!view||!$('focusLength')||!$('breakLength')){if(n)setTimeout(()=>wait(n-1),100);return}if($('publicPlantCard'))return;mount(view)}
  function mount(view){const card=document.createElement('div');card.id='publicPlantCard';card.className='panel plant-card';card.innerHTML=`<div class="plant-art" id="plantArt"></div><div class="plant-title" id="plantTitle"></div><div class="plant-minutes" id="plantMinutes"></div><div class="plant-progress"><i id="plantProgressFill"></i></div><div class="plant-stage" id="plantStage"></div><div class="plant-picker"><button class="plant-pick" data-plant="sunflower">🌻 Sunflower</button><button class="plant-pick" data-plant="cactus">🌵 Cactus</button><button class="plant-pick" data-plant="flower">🌸 Cherry Blossom</button></div><button class="secondary-btn garden-btn" id="gardenToggle">🌿 My Garden</button><div class="garden-panel" id="gardenPanel"><h3>My Garden</h3><div class="garden-grid" id="gardenGrid"></div></div>`;const sectionHead=view.querySelector('.section-head');sectionHead?.insertAdjacentElement('afterend',card);card.querySelectorAll('[data-plant]').forEach(b=>b.onclick=()=>choose(b.dataset.plant));$('gardenToggle').onclick=()=>{$('gardenPanel').classList.toggle('open');renderGarden()};installTimer();render()}
  function choose(id){const s=state();if(s.minutes>0&&s.active!==id)return;s.active=id;s.justCompleted=false;s.growthStage=1;saveState(s);render()}
  function render(){if(!$('plantArt')||!currentUser)return;const s=state(),p=plants[s.active]||plants.sunflower,st=s.growthStage;$('plantArt').textContent=p.stages[st-1];$('plantArt').className='plant-art stage-'+st;$('plantTitle').textContent=`Growing ${p.name} ${p.full}`;$('plantMinutes').textContent=`${Math.min(120,s.minutes)} / 120 minutes`;$('plantProgressFill').style.width=Math.min(100,s.minutes/120*100)+'%';$('plantStage').textContent=`Stage ${st} of 5${st===5?' · Fully grown':''}`;document.querySelectorAll('#publicPlantCard [data-plant]').forEach(b=>{b.classList.toggle('active',b.dataset.plant===s.active);b.disabled=s.minutes>0&&b.dataset.plant!==s.active});renderGarden()}
  function renderGarden(){if(!$('gardenGrid')||!currentUser)return;const s=state();$('gardenGrid').innerHTML=s.garden.length?s.garden.slice().reverse().map(x=>`<div class="garden-item"><span class="emoji">${plants[x.type]?.full||'🌿'}</span><b>${plants[x.type]?.name||'Plant'}</b><small>Completed ${new Date(x.completed).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></div>`).join(''):'<div class="garden-empty">No fully grown plants yet. Finish 120 focus minutes to grow your first one 🌱</div>'}
  function celebratePlant(p){const layer=document.createElement('div');layer.className='focus-celebration';for(let i=0;i<18;i++){const e=document.createElement('span');e.className='focus-petal';e.textContent=i%2?'🌸':'✨';e.style.left=(Math.random()*100)+'vw';e.style.animationDelay=(Math.random()*.5)+'s';layer.appendChild(e)}document.body.appendChild(layer);setTimeout(()=>layer.remove(),2300);if(typeof notice==='function')notice(`Your ${p.name} is fully grown! ${p.full}`);else setTimeout(()=>alert(`Your ${p.name} is fully grown! ${p.full}`),0)}
  function addMinutes(min){if(!currentUser||!min||min<1)return;const d=ensureData();d.focusMinutes=(+d.focusMinutes||0)+min;saveData(d);const s=state(),p=plants[s.active]||plants.sunflower;if(s.justCompleted)return;s.minutes=Math.min(120,s.minutes+min);s.growthStage=stage(s.minutes);if(s.minutes>=120){s.garden.push({id:crypto.randomUUID(),type:s.active,completed:new Date().toISOString()});s.justCompleted=true;saveState(s);render();celebratePlant(p);setTimeout(()=>{const latest=state();if(latest.justCompleted&&latest.minutes>=120){latest.minutes=0;latest.growthStage=1;latest.justCompleted=false;saveState(latest);render()}},1800)}else{saveState(s);render()}if(typeof renderBetterProgress==='function')renderBetterProgress()}
  function installTimer(){if(window.__publicGardenTimerInstalled)return;window.__publicGardenTimerInstalled=true;const toggle=$('timerToggle'),reset=$('timerReset'),label=$('timerLabel');let mode='focus';const saved=ensureData().timerPrefs||{focus:25,break:5};$('focusLength').value=Math.max(1,Math.min(180,+saved.focus||25));$('breakLength').value=Math.max(1,Math.min(60,+saved.break||5));const focusMin=()=>Math.max(1,Math.min(180,+$('focusLength').value||25)),breakMin=()=>Math.max(1,Math.min(60,+$('breakLength').value||5));const setMode=m=>{mode=m;timerSeconds=(m==='focus'?focusMin():breakMin())*60;if(label)label.textContent=m==='focus'?'Focus session':'Break time';timerRender()};clearInterval(timerInterval);timerRunning=false;setMode('focus');toggle.textContent='Start';toggle.onclick=()=>{timerRunning=!timerRunning;toggle.textContent=timerRunning?'Pause':'Start';if(timerRunning){timerInterval=setInterval(()=>{timerSeconds--;if(timerSeconds<=0){clearInterval(timerInterval);timerRunning=false;toggle.textContent='Start';if(mode==='focus'){const mins=focusMin();addMinutes(mins);mode='break';timerSeconds=breakMin()*60;if(label)label.textContent='Break time';if(typeof notice==='function')notice(`Focus complete — ${mins} minutes grew your plant 🌱`)}else{mode='focus';timerSeconds=focusMin()*60;if(label)label.textContent='Focus session';if(typeof notice==='function')notice('Break complete — ready to focus again?')}timerRender();return}timerRender()},1000)}else clearInterval(timerInterval)};reset.onclick=()=>{clearInterval(timerInterval);timerRunning=false;toggle.textContent='Start';setMode('focus')};$('focusLength').onchange=()=>{const d=ensureData();d.timerPrefs={focus:focusMin(),break:breakMin()};saveData(d);if(!timerRunning&&mode==='focus')setMode('focus')};$('breakLength').onchange=()=>{const d=ensureData();d.timerPrefs={focus:focusMin(),break:breakMin()};saveData(d);if(!timerRunning&&mode==='break')setMode('break')}}
  const prevEnter=typeof enterApp==='function'?enterApp:null;if(prevEnter){enterApp=function(name){prevEnter(name);setTimeout(render,0)}}window.addEventListener('storage',render);wait();
})();