(() => {
  const $=id=>document.getElementById(id), VIEW_KEY='plannerViewV3';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const iso=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
  const fmt=d=>new Date(d+'T00:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric'}).toUpperCase();
  let month=new Date();month.setDate(1);let selected=iso(new Date());
  const wait=(n=50)=>{const v=$('view-planner');if(!v||typeof ensureData!=='function'){if(n)setTimeout(()=>wait(n-1),100);return}if($('publicPlannerV3'))return;mount(v)};wait();
  function get(){try{return ensureData()}catch{return null}}
  function examInfo(){try{const d=get();return d?.exam?.date?{date:d.exam.date,name:d.exam.name||'Exam'}:null}catch{return null}}
  function mount(view){
    const oldPanels=[...view.querySelectorAll(':scope > .panel')],oldList=$('planList');oldPanels.forEach(p=>p.style.display='none');if(oldList)oldList.style.display='none';
    const box=document.createElement('div');box.id='publicPlannerV3';box.className='panel planner-v3';box.innerHTML=`<div class="section-head" style="margin-top:0"><div><h2>Planner</h2><p>Plan in a list or monthly calendar. Both views use the same saved tasks.</p></div></div><div class="planner-view-toggle"><button data-pview="list">List View</button><button data-pview="calendar">Calendar View</button></div><div class="planner-v3-add"><input type="date" id="pubPvDate"><input id="pubPvTopic" placeholder="Subject / topic"><input id="pubPvTask" placeholder="Study task"><button class="primary-btn compact" id="pubPvAdd">Add task</button></div><div id="pubPvList"></div><div id="pubPvCalendar" style="display:none"></div>`;
    view.appendChild(box);$('pubPvDate').value=selected;$('pubPvAdd').onclick=add;box.querySelectorAll('[data-pview]').forEach(b=>b.onclick=()=>setView(b.dataset.pview));setView(localStorage.getItem(VIEW_KEY)||'list')
  }
  function add(){const d=get(),date=$('pubPvDate').value,topic=$('pubPvTopic').value.trim(),task=$('pubPvTask').value.trim();if(!d||!date||!topic||!task)return;d.plans ||= [];d.plans.push({id:crypto.randomUUID(),date,topic,task,done:false});saveData(d);$('pubPvTopic').value='';$('pubPvTask').value='';selected=date;render()}
  function setView(v){localStorage.setItem(VIEW_KEY,v);document.querySelectorAll('[data-pview]').forEach(b=>b.classList.toggle('active',b.dataset.pview===v));$('pubPvList').style.display=v==='list'?'block':'none';$('pubPvCalendar').style.display=v==='calendar'?'block':'none';render()}
  function render(){renderList();renderCalendar()}
  function renderList(){const d=get();if(!d)return;const rows=[...(d.plans||[])].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));const groups={};rows.forEach(r=>(groups[r.date||'No date']||=[]).push(r));$('pubPvList').innerHTML=rows.length?Object.entries(groups).map(([date,items])=>`<div class="planner-date-group"><div class="planner-date-title">${date==='No date'?'NO DATE':fmt(date)}</div>${items.map(r=>`<div class="planner-task-row ${r.done?'planner-complete':''}"><div><b>${esc(r.topic)}</b><small>${esc(r.task)}</small></div><div class="planner-task-actions"><button data-toggle="${r.id}">${r.done?'↺':'✓'}</button><button data-edit="${r.id}">Edit</button><button data-del="${r.id}">×</button></div></div>`).join('')}</div>`).join(''):'<p class="planner-empty">No planner tasks yet.</p>';bind()}
  function bind(){document.querySelectorAll('#pubPvList [data-toggle]').forEach(b=>b.onclick=()=>{const d=get(),r=(d.plans||[]).find(x=>x.id===b.dataset.toggle);if(r){r.done=!r.done;saveData(d);render()}});document.querySelectorAll('#pubPvList [data-del]').forEach(b=>b.onclick=()=>{const d=get();d.plans=(d.plans||[]).filter(x=>x.id!==b.dataset.del);saveData(d);render()});document.querySelectorAll('#pubPvList [data-edit]').forEach(b=>b.onclick=()=>{const d=get(),r=(d.plans||[]).find(x=>x.id===b.dataset.edit);if(!r)return;const t=prompt('Edit task',r.task);if(t===null)return;const s=prompt('Edit subject/topic',r.topic);if(s===null)return;r.task=t.trim()||r.task;r.topic=s.trim()||r.topic;saveData(d);render()})}
  function renderCalendar(){const holder=$('pubPvCalendar');if(!holder)return;const d=get();if(!d)return;const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate(),tasks=d.plans||[],today=iso(new Date()),exam=examInfo();let cells='';for(let i=0;i<42;i++){let dt,muted=false;if(i<start){dt=new Date(y,m-1,prevDays-start+i+1);muted=true}else if(i>=start+days){dt=new Date(y,m+1,i-start-days+1);muted=true}else dt=new Date(y,m,i-start+1);const key=iso(dt),items=tasks.filter(x=>x.date===key),isExam=exam?.date===key;cells+=`<button class="planner-day ${muted?'muted':''} ${key===today?'today':''} ${key===selected?'selected':''} ${items.length?'has-task':''} ${isExam?'exam':''}" data-date="${key}"><span class="planner-day-num">${dt.getDate()}</span><div class="planner-day-items">${items.slice(0,2).map(x=>esc(x.topic)).join('<br>')}${isExam?'<br>★ '+esc(exam.name):''}</div></button>`}holder.innerHTML=`<div class="planner-calendar-head"><button id="pubPvPrev">←</button><h3>${month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h3><button id="pubPvNext">→</button></div><div class="planner-calendar"><div class="planner-dow">Mon</div><div class="planner-dow">Tue</div><div class="planner-dow">Wed</div><div class="planner-dow">Thu</div><div class="planner-dow">Fri</div><div class="planner-dow">Sat</div><div class="planner-dow">Sun</div>${cells}</div><div class="planner-selected-day" id="pubPvSelected"></div>`;$('pubPvPrev').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$('pubPvNext').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()};holder.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.date;$('pubPvDate').value=selected;const x=new Date(selected+'T00:00:00');month=new Date(x.getFullYear(),x.getMonth(),1);renderCalendar()});renderSelected(tasks,exam)}
  function renderSelected(tasks,exam){const items=tasks.filter(x=>x.date===selected),isExam=exam?.date===selected;$('pubPvSelected').innerHTML=`<div class="planner-date-title">${fmt(selected)}</div>${isExam?`<div class="planner-task-row"><div><b>★ ${esc(exam.name)}</b><small>Exam date</small></div></div>`:''}${items.length?items.map(x=>`<div class="planner-task-row ${x.done?'planner-complete':''}"><div><b>${esc(x.topic)}</b><small>${esc(x.task)}</small></div></div>`).join(''):'<p class="planner-empty">No tasks yet. The add form above is already set to this date.</p>'}`}
  window.addEventListener('storage',render);
})();